# Generated by Django 5.2.17 on 2026-09-16 14:07

from django.db import migrations, models

import django_admin_index.translations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_index", "0006_auto_20230503_1910"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appgroup",
            name="translations",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='A JSON-object that uses the Django language code as key and the localized name as value. If no translation can be found for the active language, the name is used as fallback. Example: {"en": "File", "nl": "Bestand"}',
                validators=[
                    django_admin_index.translations.validate_translation_json_format
                ],
                verbose_name="translations",
            ),
        ),
        migrations.AlterField(
            model_name="applink",
            name="translations",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='A JSON-object that uses the Django language code as key and the localized name as value. If no translation can be found for the active language, the name is used as fallback. Example: {"en": "File", "nl": "Bestand"}',
                validators=[
                    django_admin_index.translations.validate_translation_json_format
                ],
                verbose_name="translations",
            ),
        ),
    ]
