name: Code quality checks

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
  schedule:
    - cron: "36 4 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  linting:
    name: Code-quality checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv:
          - isort
          - black
          - flake8
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: 'pyproject.toml'
      - name: Install dependencies
        run: pip install tox
      - run: tox --colored=yes
        env:
          TOXENV: ${{ matrix.toxenv }}
          FORCE_COLOR: "1"

  zizmor:
    name: GitHub Actions Security Analysis with zizmor 🌈
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e # v0.5.3
