name: Code quality checks

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
  schedule:
    - cron: "36 4 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  linting:
    name: Code-quality checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv:
          - isort
          - black
          - flake8
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version-file: 'pyproject.toml'
      - name: Install dependencies
        run: pip install tox
      - run: tox --colored=yes
        env:
          TOXENV: ${{ matrix.toxenv }}
          FORCE_COLOR: "1"

  zizmor:
    name: GitHub Actions Security Analysis with zizmor 🌈
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@cc914d7f3750a2d13d75c7f184a1060aa0e9d482 # v0.6.4
