name: Code quality checks

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - master
    tags:
      - '*'
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  linting:
    name: Code-quality checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv:
          - isort
          - black
          - flake8
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install tox
      - run: tox
        env:
          TOXENV: ${{ matrix.toxenv }}
